### ISSUE TITLE
failed to init L1: failed to get L1 RPC client: failed to dial L1 address

### ISSUE THREAD

**Issue by webhype** [base-org/node#224]
Hey guys, trying to set a fullnode on Ubuntu 22.04 and it's been frustrating and confusing to say the least. The instructions don't make clear at all what the different fields in the composer file even mean, and what are the clear boundaries between my L1 node and the BASE node. 

The specific problem is, my base Docker node seems unable to connect to my L1 geth node at http://localhost:8545. I have verified that `localhost:8545` is up and running and works as expected to send ETH transactions.

From .env.mainnet:
```
# [recommended] replace with your preferred L1 (Ethereum, not Base) node RPC URL:
OP_NODE_L1_ETH_RPC=http://localhost:8545
```
My docker-compose.yml:
```
version: '3.8'

services:
  geth: # this is Optimism's geth client
    build: .
    ports:
      # https://github.com/base-org/node/issues/79
      - 8645:8545       # RPC - changed to avoid port conflict
      # https://github.com/base-org/node/issues/79
      - 8646:8546       # websocket - changed to avoid port conflict
      - 36303:30303     # P2P TCP (currently unused) - changed to avoid port conflict
      - 36303:30303/udp # P2P UDP (currently unused) - changed to avoid port conflict
      - 7301:6060       # metrics
    command: [ "bash", "./geth-entrypoint" ]
    volumes:
        - ${GETH_HOST_DATA_DIR}:/data
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet
  node:
    build: .
    depends_on:
      - geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet
```
It seems like the BASE node can't connect to the world outside of the Docker container, i.e. it can't "see" localhost:8545 from inside its container.

I tried this change to .env.mainnet, but it didn't help:
```
OP_NODE_L1_ETH_RPC=http://host.docker.internal:8545
```

The exact log output of the error is:
```
node_1  | t=2024-03-26T15:41:58+0000 lvl=eror msg="Error initializing the rollup node" err="failed to init L1: failed to get L1 RPC client: failed to dial L1 address (http://host.docker.internal:8545): operation failed permanently after 10 attempts: address unavailable (http://host.docker.internal:8545)"
node_1  | t=2024-03-26T15:41:58+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node: failed to init L1: failed to get L1 RPC client: failed to dial L1 address (http://host.docker.internal:8545): operation failed permanently after 10 attempts: address unavailable (http://host.docker.internal:8545)"
base-fullnode_node_1 exited with code 1
```
