### ISSUE TITLE
Suggestion to lock down 8545 and 8546 from outside access? (prevent globbing on to 0.0.0.0)

### ISSUE THREAD

**Issue by webhype** [base-org/node#237]
I am referring to the following sections in the fullnode docker-compose file, all these services glob on to 0.0.0.0 - is there a reason why this is configured so insecure by default? 
```
geth:
    ports:
      - 8545:8545       # RPC
      - 8546:8546       # websocket
      - 30303:30303     # P2P TCP (currently unused) 
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060       # metrics

node:
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
```
How would I reconfigure this to glob on to only 127.0.0.1 or a local address like 172.17.0.2? I am aware of `ufw` and such, but I feel there's no reason to glob on to all IPs in the first place, so two layers of security are better than one. 

THanks ❤️
