### ISSUE TITLE
Error initializing the rollup node / missing trie node 

### ISSUE THREAD

**Issue by webhype** [base-org/node#238]
```
node-1  | t=2024-04-07T19:18:42+0000 lvl=eror msg="Error initializing the rollup node" 
err="failed to init the runtime config: failed to load runtime configuration repeatedly, 
last error: operation failed permanently after 5 attempts: 
failed to fetch unsafe block signing address from system config: 
missing trie node 5c29c01b6201487ec9b7cea38fd44fadbc02eb8d13587feeed2a1b1c909df457 (path ) 
state 0x5c29c01b6201487ec9b7cea38fd44fadbc02eb8d13587feeed2a1b1c909df457 
is not available, not found"
```
Any suggestions? Thanks!

My docker-compose file looks as follows:
```
version: '3.8'

services:
  geth: # this is Optimism's geth client
    build: .
    ports:
      # https://github.com/base-org/node/issues/79
      - 9545:8545       # RPC 🚨 changed to avoid port conflict
      # https://github.com/base-org/node/issues/79
      - 9546:8546       # websocket 🚨 changed to avoid port conflict
      - 36303:30303     # P2P TCP (currently unused)  # 🚨 changed to avoid port conflict
      - 36303:30303/udp # P2P UDP (currently unused)  # 🚨 changed to avoid port conflict
      - 7301:6060       # metrics
    command: [ "bash", "./geth-entrypoint" ]
    volumes:
      - ${GETH_HOST_DATA_DIR}:/data
    env_file:
      # select your network here:
      - .env.mainnet   # 🚨 changed to choose mainnet

  node:
    build: .
    depends_on:
      - geth
    ports:
      - 7545:9545     # RPC 🚨 changed with 9545 from above
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
      # select your network here:
      - .env.mainnet  # 🚨 changed to choose mainnet
 ```
The only two lines changed in `.env.mainnet`, vs. what's in the repo, are the following:
```
OP_NODE_L1_ETH_RPC=http://172.17.0.1:8545
OP_NODE_L1_BEACON=http://172.17.0.1:5052
```
