### ISSUE TITLE
Unable to launch Base node | Application fails L1 Beacon check

### ISSUE THREAD

**Issue by klestrong** [base-org/node#324]
I'm trying to run Base node in a Kubernetes cluster. Upon Base node startup, log indicates "Unknown env var" for OP_NODE_L2_ENGINE_AUTH_RAW and also indicates "Application failed" after failing L1 Beacon check. I successfully checked connectivity between the Base execution pod (10.44.2.12) and my L1 Beacon pod (10.44.2.9) by using ping. Could the "connection refused" L1 Beacon reply be a result of the "Unknown env var" error for the L2 engine auth key? My log output is in the image below.

![base_support_log](https://github.com/user-attachments/assets/251339bb-9de1-4e18-ab61-ddb9ec849495)

My pods are listed below with corresponding IPs.

![image](https://github.com/user-attachments/assets/266ebbdf-8b1b-413a-b820-358d44038b67)

Below is my environment config file.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-base-cluster1-1a-config-env
data:
  RETH_CHAIN: "base"
  RETH_SEQUENCER_HTTP: https://mainnet-sequencer.base.org
  OP_GETH_SEQUENCER_HTTP: https://mainnet-sequencer.base.org
  
  # [optional] used to enable geth stats:
  # OP_GETH_ETH_STATS: nodename:secret@host:port
  
  # [required] replace with your preferred L1 (Ethereum, not Base) node RPC URL:
  #OP_NODE_L1_ETH_RPC: https://1rpc.io/eth
  OP_NODE_L1_ETH_RPC: https://mainnet.<my L1 Eth host>.com
  
  # [required] replace with your preferred L1 CL beacon endpoint:
  #OP_NODE_L1_BEACON: https://your.mainnet.beacon.node/endpoint-here
  OP_NODE_L1_BEACON: http://10.44.2.9:8551
  
  # auth secret used by op-geth engine API:
  #OP_NODE_L2_ENGINE_AUTH_RAW: 688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a
  OP_NODE_L2_ENGINE_AUTH_RAW: c169< my jwt secret >d4d7
  
  OP_NODE_L2_ENGINE_AUTH: /tmp/engine-auth-jwt
  #OP_NODE_L2_ENGINE_RPC: ws://execution:8551
  OP_NODE_L2_ENGINE_RPC: ws://localhost:8551
  OP_NODE_LOG_LEVEL: "info"
  OP_NODE_METRICS_ADDR: 0.0.0.0
  OP_NODE_METRICS_ENABLED: "true"
  OP_NODE_METRICS_PORT: "7300"
  OP_NODE_NETWORK: "base-mainnet"
  OP_NODE_P2P_AGENT: "base"
  OP_NODE_P2P_BOOTNODES: enr:-J24QNz9lbrKbN4iSmmjtnr7SjUMk4zB7f1krHZcTZx-JRKZd0kA2gjufUROD6T3sOWDVDnFJRvqBBo62zuF-hYCohOGAYiOoEyEgmlkgnY0gmlwhAPniryHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQKNVFlCxh_B-716tTs-h1vMzZkSs1FTu_OYTNjgufplG4N0Y3CCJAaDdWRwgiQG,enr:-J24QH-f1wt99sfpHy4c0QJM-NfmsIfmlLAMMcgZCUEgKG_BBYFc6FwYgaMJMQN5dsRBJApIok0jFn-9CS842lGpLmqGAYiOoDRAgmlkgnY0gmlwhLhIgb2Hb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJ9FTIv8B9myn1MWaC_2lJ-sMoeCDkusCsk4BYHjjCq04N0Y3CCJAaDdWRwgiQG,enr:-J24QDXyyxvQYsd0yfsN0cRr1lZ1N11zGTplMNlW4xNEc7LkPXh0NAJ9iSOVdRO95GPYAIc6xmyoCCG6_0JxdL3a0zaGAYiOoAjFgmlkgnY0gmlwhAPckbGHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQJwoS7tzwxqXSyFL7g0JM-KWVbgvjfB8JA__T7yY_cYboN0Y3CCJAaDdWRwgiQG,enr:-J24QHmGyBwUZXIcsGYMaUqGGSl4CFdx9Tozu-vQCn5bHIQbR7On7dZbU61vYvfrJr30t0iahSqhc64J46MnUO2JvQaGAYiOoCKKgmlkgnY0gmlwhAPnCzSHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQINc4fSijfbNIiGhcgvwjsjxVFJHUstK9L1T8OTKUjgloN0Y3CCJAaDdWRwgiQG,enr:-J24QG3ypT4xSu0gjb5PABCmVxZqBjVw9ca7pvsI8jl4KATYAnxBmfkaIuEqy9sKvDHKuNCsy57WwK9wTt2aQgcaDDyGAYiOoGAXgmlkgnY0gmlwhDbGmZaHb3BzdGFja4OFQgCJc2VjcDI1NmsxoQIeAK_--tcLEiu7HvoUlbV52MspE0uCocsx1f_rYvRenIN0Y3CCJAaDdWRwgiQG
  OP_NODE_P2P_LISTEN_IP: 0.0.0.0
  OP_NODE_P2P_LISTEN_TCP_PORT: "9222"
  OP_NODE_P2P_LISTEN_UDP_PORT: "9222"
  OP_NODE_RPC_ADDR: "0.0.0.0"
  OP_NODE_RPC_PORT: "7545"
  OP_NODE_SNAPSHOT_LOG: /tmp/op-node-snapshot-log
  OP_NODE_VERIFIER_L1_CONFS: "4"
  OP_NODE_ROLLUP_LOAD_PROTOCOL_VERSIONS: "true"
  
  OP_NODE_L1_TRUST_RPC: "true"
```
