### ISSUE TITLE
Blocks don't arrive every 2 seconds and the block head is usually 30-40+ blocks behind network

### ISSUE THREAD

**Issue by damiensgit** [base-org/node#84]
Symptoms: Blocks don't arrive every 2 seconds and are usually 30-40 blocks behind.

Environment:

Ubuntu 20.04

Note: Running base node and l1 on same machine.

L1: Prysm v4.0.7 + nethermind 1.20.1

docket-compose:
```
services:
  geth: # this is Optimism's geth client
    build: .
    ports:
      - 28545:8545       # RPC
      - 28546:8546       # websocket
      - 26656:30303     # P2P TCP (currently unused)
      - 26656:30303/udp # P2P UDP (currently unused)
    command: [ "sh", "./geth-entrypoint" ]
    env_file:
      - .env.mainnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /geth:/data
  node:
    build: .
    depends_on:
      - geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    command: [ "sh", "./op-node-entrypoint" ]
    env_file:
      - .env.mainnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
